"""Create and seed the SQLite database that backs the API.

Sources
  data/words.json          the curated 5,000-word dictionary (generated by
                           tools/build_dictionary.py)      -> chinese_words
  data/chars.json          character -> readings           -> char_pinyin
  .tmp/phrase_pinyin.txt   ~412k context-correct phrases   -> phrase_pinyin
                           (optional; run tools/fetch_data.py first)

The phrase table is what makes the server-side lookup resolve polyphones
properly, so the script warns loudly when it is missing.

Run:
  python tools/build_database.py                 # build var/trainer.db
  python tools/build_database.py --db test.db --force
  python tools/build_database.py --no-phrases    # words + characters only
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from server.db import Database  # noqa: E402
from server.pinyin_engine import to_numbers, to_plain  # noqa: E402

DATA = ROOT / "data"
TMP = ROOT / ".tmp"
DEFAULT_DB = ROOT / "var" / "trainer.db"

CJK_RE = re.compile(r"^[\u4e00-\u9fff]+$")
SYLLABLE_RE = re.compile(r"^[a-zA-Z\u00c0-\u024f\u00fc\u00dc]+$")


def load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def seed_words(db: Database, words: list[dict], now: int) -> int:
    rows = []
    for word in words:
        pinyin = word["p"]
        syllables = [token for token in pinyin.split() if token]
        rows.append((
            word["s"],
            word.get("t"),
            pinyin,
            to_plain(pinyin),
            to_numbers(pinyin),
            json.dumps(syllables, ensure_ascii=False),
            int(word.get("f") or 0),
            int(word.get("r") or 0),
            word.get("c") or "other",
            int(word.get("lv") or 3),
            len(syllables),
            now,
        ))
    return db.bulk_insert(
        "INSERT INTO chinese_words"
        " (simplified, traditional, pinyin, pinyin_plain, pinyin_numbers, syllables,"
        "  frequency, frequency_rank, category, difficulty_level, syllable_count, created_at)"
        " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)"
        " ON CONFLICT (simplified) DO UPDATE SET"
        "   traditional = excluded.traditional, pinyin = excluded.pinyin,"
        "   pinyin_plain = excluded.pinyin_plain, pinyin_numbers = excluded.pinyin_numbers,"
        "   syllables = excluded.syllables, frequency = excluded.frequency,"
        "   frequency_rank = excluded.frequency_rank, category = excluded.category,"
        "   difficulty_level = excluded.difficulty_level, syllable_count = excluded.syllable_count",
        rows,
    )


def seed_chars(db: Database, chars: dict[str, list[str]]) -> int:
    rows = [(char, json.dumps(readings, ensure_ascii=False)) for char, readings in chars.items()]
    return db.bulk_insert(
        "INSERT INTO char_pinyin (char, readings) VALUES (?, ?)"
        " ON CONFLICT (char) DO UPDATE SET readings = excluded.readings",
        rows,
    )


def seed_phrases(db: Database, path: Path, limit: int | None = None) -> int:
    """phrase_pinyin.txt lines look like: 学校: xué xiào"""
    rows = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.split("#")[0].strip()
            if not line or ":" not in line:
                continue
            phrase, _, readings = line.partition(":")
            phrase = phrase.strip()
            if not CJK_RE.match(phrase):
                continue
            syllables = readings.split()
            if len(syllables) != len(phrase):
                continue
            if not all(SYLLABLE_RE.match(token) for token in syllables):
                continue
            rows.append((phrase, " ".join(token.lower() for token in syllables)))
            if limit and len(rows) >= limit:
                break
    return db.bulk_insert(
        "INSERT INTO phrase_pinyin (phrase, syllables) VALUES (?, ?)"
        " ON CONFLICT (phrase) DO UPDATE SET syllables = excluded.syllables",
        rows,
        chunk=20000,
    )


def seed_script_map(db: Database, path: Path) -> int:
    """data/script.json holds both directions of the character script map.

    `st`       simplified -> first traditional form (used for display)
    `variants` traditional -> simplified, covering EVERY variant, so traditional
               input normalises to simplified before matching the phrase table.
    """
    if not path.exists():
        return 0
    doc = json.loads(path.read_text(encoding="utf-8"))
    pairs: set[tuple[str, str]] = set()
    for simplified, traditional in (doc.get("st") or {}).items():
        pairs.add((simplified, traditional))
    for traditional, simplified in (doc.get("variants") or {}).items():
        pairs.add((simplified, traditional))
    return db.bulk_insert(
        "INSERT INTO script_map (simplified, traditional) VALUES (?, ?)"
        " ON CONFLICT (simplified, traditional) DO NOTHING",
        sorted(pairs),
    )


def migrate_script_map(db: Database) -> bool:
    """Drop script_map when it still has the old single-column primary key.

    The table is derived entirely from data/script.json, so rebuilding it is
    cheaper and safer than trying to alter it in place. init_schema() recreates it.
    """
    if not db.table_exists("script_map"):
        return False
    columns = db.query("PRAGMA table_info(script_map)")
    primary = [column["name"] for column in columns if column["pk"]]
    if primary == ["simplified"]:
        db.execute("DROP TABLE script_map")
        print("migrating   dropped the old single-column script_map table")
        return True
    return False


def main(argv: list[str] | None = None) -> int:
    # legacy console codepages cannot encode every character we print
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError, OSError):
            pass

    parser = argparse.ArgumentParser(description="Build the trainer SQLite database.")
    parser.add_argument("--db", default=str(DEFAULT_DB))
    parser.add_argument("--force", action="store_true", help="delete an existing database first")
    parser.add_argument("--no-phrases", action="store_true", help="skip the phrase table")
    parser.add_argument("--phrase-limit", type=int, default=None, help="only load N phrases (for tests)")
    args = parser.parse_args(argv)

    db_path = Path(args.db)
    if args.force and db_path.exists():
        for suffix in ("", "-wal", "-shm"):
            candidate = Path(str(db_path) + suffix)
            if candidate.exists():
                candidate.unlink()
        print(f"removed existing {db_path}")

    words_path = DATA / "words.json"
    chars_path = DATA / "chars.json"
    if not words_path.exists() or not chars_path.exists():
        print("! data/words.json or data/chars.json is missing.")
        print("  generate them first:  python tools/build_dictionary.py")
        return 1

    words = load_json(words_path)["words"]
    chars = load_json(chars_path)["chars"]
    phrase_path = TMP / "phrase_pinyin.txt"

    db = Database(db_path)
    migrate_script_map(db)
    db.init_schema()

    import time
    now = int(time.time() * 1000)

    print(f"database    {db_path}")
    print(f"seeding     {len(words):,} words …")
    inserted = seed_words(db, words, now)
    print(f"            {inserted:,} rows in chinese_words")

    print(f"seeding     {len(chars):,} characters …")
    inserted = seed_chars(db, chars)
    print(f"            {inserted:,} rows in char_pinyin")

    script_path = DATA / "script.json"
    inserted = seed_script_map(db, script_path)
    if inserted:
        print(f"seeding     {inserted:,} simplified/traditional pairs …")
        print(f"            {inserted:,} rows in script_map")
    else:
        print(f"! {script_path} missing - traditional input will not normalise for lookup.")
        print("  generate it first:  python tools/build_dictionary.py")

    if args.no_phrases:
        print("skipping    phrase table (--no-phrases)")
    elif not phrase_path.exists():
        print(f"! {phrase_path} not found - the lookup will fall back to character readings.")
        print("  run:  python tools/fetch_data.py   then rebuild for context-aware polyphones.")
    else:
        size_mb = phrase_path.stat().st_size / (1024 * 1024)
        print(f"seeding     phrases from {phrase_path.name} ({size_mb:.1f} MB) …")
        inserted = seed_phrases(db, phrase_path, args.phrase_limit)
        print(f"            {inserted:,} rows in phrase_pinyin")

    db.execute(
        "INSERT INTO users (username, display_name, created_at) VALUES ('local', 'Local learner', ?)"
        " ON CONFLICT (username) DO NOTHING",
        (now,),
    )

    counts = db.stats()
    print("\nrow counts")
    for table in sorted(counts):
        print(f"  {table:<22} {counts[table]:>9,}")
    print(f"\ndatabase size  {db_path.stat().st_size / (1024 * 1024):.1f} MB")
    print("ready.  start the server:  python -m server")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
